name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 트리거

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    # 코드 체크아웃
    - name: Checkout repository
      uses: actions/checkout@v2

    # JDK 11 설정
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Set SSH key permissions
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
        cat ~/.ssh/id_rsa

    - name: Deploy to Server
      run: scp -i ~/.ssh/id_rsa -r build/libs/*.jar ubuntu@3.38.246.161:~/app/

    - name: Run SSH commands
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@3.38.246.161 << 'EOF'
          pkill -f 'java -jar' || true
          nohup java -jar ~/app/your-spring-boot-app.jar > log.txt 2>&1 &
        EOF
